### ISSUE TITLE
Preferred Install Method

### ISSUE THREAD

**Issue by futurealecks** [higebu/vyos-cloudinit#1]
How do you suggest getting this installed on the AWS instance at launch when you need this pre-installed at creation to send user data?

Thanks

**Comment by higebu** [comment]
We need to create AMI with this package.
The procedure is following:
1. Create VyOS instance.
2. Install this package.
3. Delete hw-id of interface. `delete interface ethernet ethX hw-id`
4. Stop the instance and create AMI.

Thanks.

**Comment by futurealecks** [comment]
Great. That worked Thanks!

**Comment by higebu** [comment]
@futurealecks Sorry. I forgot one more procedure. You may want to disable `ec2-vyos-init` with `sudo update-rc.d ec2-vyos-init disable`.

**Comment by futurealecks** [comment]
Can you execute an awscli command or run a bash script on the vyos image from the vyos userdata?

**Comment by higebu** [comment]
@futurealecks  I'm sorry for the delay in my response. You can execute bash script. vbash is modified bash.

**Comment by higebu** [comment]
@futurealecks I published AMIs with vyos-cloudinit and  awscli. See https://github.com/higebu/vyos-cloudinit/blob/master/README.md#ami
