### ISSUE TITLE
VyOS on OpenStack, tries to fetch ssh public-key from EC2 metadata URL

### ISSUE THREAD

**Issue by mapolone** [higebu/vyos-cloudinit#10]
Hello,
I'm building an image for OpenStack, based on VyOS 1.1.7, with vyos-cloudinit 0.3.1.
Once set `service cloudinit` to `openstack`:

```
service {
    cloudinit {
        environment openstack
     }
}
```

Trying to start service here's what I get:
`Starting vyos-cloudinit... could not retrieve user-data from http://169.254.169.254/latest/user_data`

Looking further in configuration, previous URL is related to EC2. Even if I set `ssh-key` with correct URL for OpenStack (that is, `http://169.254.169.254/latest/meta-data/public-keys//0/openssh-key`) still tries to reach ECS metadata URL.

I'm still looking into it, do you have any clue?

**Comment by andamasov** [comment]
no cloud-init in 1.1.x
